.gitignore, examples/cwrapper_gemm/make.inc, examples/fortranModule_caxpy/make.inc, examples/fortranWrapper_ssymm/Makefile, examples/fortranWrapper_ssymm/make.inc, examples/gemm/make.inc, examples/geqr2/make.inc, examples/mdspan/make.inc
Hi Weslley! This PR should resolve #9. I've verified that all examples affected by these changes build correctly. (Note that I didn't change or test the "eigen" example. But it didn't have the ``-ltblas`` issue.)
=> Various fixes (including removing -ltblas) for examples to build with Makefiles

include/lapack/lange.hpp, include/lapack/lansy.hpp, include/slate_api/lapack/lange.hpp, include/slate_api/lapack/lansy.hpp
One of the design ideas for \<T\>LAPACK is that the abstract routines do not perform dynamic allocation. The only routine that was allocating memory dynamically on the input directory was the `lansy` for the one and inf norms. This PR moves the dynamic allocation to the lansy wrapper.
- This PR also removes the duplicate code on `lange`.
=> Remove dynamic allocation from lansy; Remove duplicate code on lange

docs/groups.dox, include/plugins/tlapack_abstractArray.hpp
The semantics of how a <T>LAPACK routine works with data was not written anywhere. This PR adds the documentation to the plugin `abstractArray.hpp`. This file has two purposes:
1. It serves as a template for writing <T>LAPACK abstract arrays.
2. It is used by Doxygen to generate the documentation.
=> Improve documentation of the <T>LAPACK abstract array

examples/eigen/example_eigen.cpp, include/lapack/geqr2.hpp, include/lapack/lanhe.hpp, include/lapack/lansy.hpp, include/lapack/larft.hpp, include/lapack/org2r.hpp, include/lapack/orm2r.hpp, include/lapack/potrf.hpp, include/lapack/potrf2.hpp, include/lapack/unmqr.hpp, include/plugins/tlapack_abstractArray.hpp, include/plugins/tlapack_eigen.hpp, include/plugins/tlapack_legacyArray.hpp, include/plugins/tlapack_mdspan.hpp, include/plugins/tlapack_stdvector.hpp
Use `slice` to represent the block operations on both matrices and vectors like proposed on #26. It considerably reduces the wordiness of the code. I personally like the way the code looks now. Note that I maintained the block operations: `row`, `rows`, `col` and `cols`. Any other suggestion on this thread, @thijssteel ?
=> Implement the idea from @thijssteel on #26

examples/eigen/README.md, examples/eigen/example_eigen.cpp, examples/geqr2/README.md, examples/geqr2/example_geqr2.cpp, include/lapack/larf.hpp, include/lapack/ung2r.hpp, include/lapack/unm2r.hpp, include/legacy_api/lapack.hpp, include/legacy_api/lapack/ung2r.hpp, include/legacy_api/lapack/unm2r.hpp, include/tlapack.hpp
In LAPACK there is a clear distinction between Orthogonal and Unitary complex matrices on the interface. Routines dealing with orthogonal matrices start with `SOR` and `DOR`; while the equivalent routines for unitary complex matrices start with `CUN` and `ZUN`. This distinction do not interfere on the major design since every routine has a defined type on Fortran. On \<T\>LAPACK, we should avoid such distinction since the data type is a template argument.
This PR replaces `org2r` by `ung2r` and `orm2r` by `unm2r` and updates the documentation.
=> Use unitary instead of orthogonal

include/lapack/geqr2.hpp, include/lapack/larf.hpp, include/lapack/larfg.hpp
Closes #35 and #31 
Fixing Issue #35 is a bit more difficult than I thought.
I could think of the following 
- make a copy of `v` inside `larf`, requiring some extra workspace and set `v[0]` to 1
- instead of calling `gemv` and `ger`, we do the calculation using loops
- we call `gemv` and `ger' on submatrices and then add the parts we skipped later
- use a specialized vector class that returns 1.0 for index 0 and v[i] otherwise
This PR is an attempt at the last option.
I can't get the type trait to work, but otherwise, it should be finished.
=> Fix #35 ( and accidentally also fixed #31)

include/lapack/larfb.hpp
It is unusual to throw any error if the workspace is larger than the necessary. This PR fixes `larf` and `larfb`. Now all the routines shall accept workspace larger than the necessary. Thanks to @thijssteel for finding this issue!
=> Fix workspace in larf and larfb.

cmake/FetchPackage.cmake, test/CMakeLists.txt, test/src/test_utils.cpp, test/tests_main.cpp
This PR adds the option to include tests on `test/src`. It is basically a work on CMake to make the tests work. I add a single test to `test/src` to verify the it is working.
* The macro FetchPackage was updated: it did not make sense to check `${pkg}_DIR` right after calling `find_package`.
=> Add the option to include tests on `test/src`

examples/geqr2/example_geqr2.cpp
Closes #18
Thanks to @thijssteel !
__[edited:]__
What was happening:
```c++
#define blas_error_if( cond ) \
((void)0)
```
when the flag `NDEBUG` is defined. So `blas_error_if( foo(...) )` is optimized to `((void)0)`.
Thus, `blas_error_if` should be used for parameter checking only.
=> Fix bug in example geqr2

include/lapack/lanhe.hpp, include/lapack/lassq.hpp
`lassq` receives the function to compute the absolute value on its interface. This is helpful on `lanhe` because we need to access only the real part in the diagonal. Using this additional parameter, we do not need to copy data. This strategy is already in place.
This PR introduces cosmetic changes to pass the absolute function as an argument to the `lassq` (using lambda function), instead of passing as a template argument. This is also a question: what code is the best in terms of abstraction? There is no rush to decide, this is just an idea that I had in mind and wanted to share.
I didn't put this on the discussion section __Ideas__ because I wanted to show how the current code would look like in practice.
=> Try use of lambda function on lassq

examples/eigenvalues/example_eigenvalues.cpp, include/lapack/gehrd.hpp, include/lapack/lahqr.hpp, include/lapack/lahr2.hpp, include/plugins/tlapack_legacyArray.hpp, include/tlapack.hpp
Blocked Hessenberg reduction
Based on my unblocked eigenvalue PR, so that one should be merged first.
This also contains my attempt at making the options work for blocksize and workspace.
Advantage of this style for opts: clean, fully type checked, not complicated overloading to access options
Disadvantage: does not allow users to use one big 'opts' and use it for all their calls
=> Blocked hessenberg reduction

include/lapack/gehrd.hpp, include/lapack/schur_move.hpp, include/lapack/schur_swap.hpp, include/lapack/unghr.hpp, include/plugins/tlapack_debugutils.hpp, include/plugins/tlapack_legacyArray.hpp, include/testutils.hpp, test/include/testdefinitions.hpp, test/include/testutils.hpp, test/src/test_gehrd.cpp, test/src/test_lasy2.cpp, test/src/test_schur_move.cpp, test/src/test_schur_swap.cpp
This PR adds a new test file for the Hessenberg reduction (and also fixes a few bugs i found while writing the tests)
It is a proposal for a pattern we can use for all tests. Several things I like:
- Template test cases to test 4 types with the same code
- Parameters are generated at the top of the file and reported in the dynamic sections. If a specific case fails, CATCH2 will then report the exact parameters used. You can then comment out the generator and replace it with a fixed value to run a single case. I have also made an issue in CATCH2 to maybe support only running a single dynamic section with a command line argument.
=> Improve tests

include/blas/gemv.hpp, include/blas/hemm.hpp, include/blas/hemv.hpp, include/blas/her2k.hpp, include/blas/symm.hpp, include/blas/symv.hpp, include/blas/syr2k.hpp, include/blas/trmm.hpp, include/blas/trsm.hpp, include/legacy_api/blas/wrappers.hpp, test/src/test_gehrd.cpp
This PR makes all lv-3 BLAS routines enable optimization via optmized BLAS (using BLAS++). The file 
https://github.com/weslleyspereira/tlapack/blob/try-all-lv3-blas-with-optmizedWrappers/include/legacy_api/blas/wrappers.hpp
has the lv-3 BLAS wrappers on \<T\>LAPACK.
=> Add wrappers to all lv-3 BLAS

test/include/testdefinitions.hpp, test/include/testutils.hpp, test/src/test_gehrd.cpp, test/src/test_lasy2.cpp, test/src/test_schur_move.cpp, test/src/test_schur_swap.cpp, test/src/test_utils.cpp
Fix a couple of copyright information. This was caused by the copy-and-paste of files from the testBLAS project
=> Fix a couple of copyright information

include/base/arrayTraits.hpp, include/base/utils.hpp, include/plugins/tlapack_debugutils.hpp, include/plugins/tlapack_eigen.hpp, include/plugins/tlapack_legacyArray.hpp, include/plugins/tlapack_mdspan.hpp, include/plugins/tlapack_stdvector.hpp
implements the ideas from: https://github.com/tlapack/tlapack/discussions/51.
- Now `type_trait`, sizet_trait` and `allow_optblas` are deduced automatically.
- Hide some utilities into the namespace `internal`.
- Add the alias `tlapack::range<idx_t>` for `std::pair<idx_t,idx_t>`. Not using anywhere so far, but it should reduce wordiness.
We need tests for the utility functions! I open a new issue to relate this.
=> Deduces the type and size type automatically for matrices and vectors

include/base/types.hpp, include/lapack/transpose.hpp, include/legacy_api/base/legacyArray.hpp, include/tlapack.hpp, test/src/test_transpose.cpp
Adds an out of place transpose.
Uses recursion for efficiency.
Includes tests and nice documentation of the function.
I am well aware that transpose is usually avoided, but that does not mean we should limit the user. They may wish to have a transpose for testing.
=> add out of place recursive transpose

.github/workflows/cmake.yml, CMakeLists.txt, README.md, test/CMakeLists.txt, test/src/CMakeLists.txt
Adds flag `TLAPACK_BUILD_SINGLE_TESTER` on CMake. Default is OFF. Builds testers separately on the build directory inside `test`.
__(After the modifications)__ To include a new test you should also modify the file `test/src/CMakeLists.txt` in the following way:
- Add `add_executable( test_YOURTEST test_YOURTEST.cpp "${CMAKE_CURRENT_SOURCE_DIR}/../tests_main.cpp" )`.
- Add `test_YOURTEST` to the list in `set_target_properties`.
- Add `catch_discover_tests(test_YOURTEST)`.
I think I can improve it. But I have to look more into it.
=> Tries to mitigate the compilation time for the tests

examples/mdspan/example_mdspan.cpp, include/plugins/tlapack_mdspan.hpp
Compatibilizes with recent changes in mdspan; mdspan now uses a template for the size type.
=> Compatibilizes with recent changes in mdspan

.github/workflows/cmake.yml, CMakeLists.txt, README.md, cmake/Config.cmake.in, include/base/utils.hpp, include/blas/symv.hpp, include/legacy_api/base/types.hpp, include/legacy_api/blas.hpp, include/legacy_api/lapack/ung2r.hpp, include/optimized/wrappers.hpp, include/tblas.hpp, src/CMakeLists.txt, test/blaspp/blas/defines.h
Resolves #83 by using wrappers from LAPACK++. Then we can use `lartg` directly. Also, enables support to `csymv` and `zsymv`.
=> Fixes issue #83

include/legacy_api/blas/iamax.hpp
This allows the use of optimized iamax through the legacy interface
=> Fix wrapper to iamax to allow using optimized BLAS

.github/workflows/cmake.yml, .gitmodules, CMakeLists.txt, README.md, cmake/FetchPackage.cmake, test/CMakeLists.txt, test/src/CMakeLists.txt, test/src/test_blocked_francis.cpp, test/src/test_gehrd.cpp, test/src/test_gelq2.cpp, test/src/test_gelqf.cpp, test/src/test_lasy2.cpp, test/src/test_lauum.cpp, test/src/test_optBLAS.cpp, test/src/test_schur_move.cpp, test/src/test_schur_swap.cpp, test/src/test_transpose.cpp, test/src/test_unblocked_francis.cpp, test/src/test_unmhr.cpp, test/src/test_utils.cpp, test/tests_main.cpp
Closes #115 
From https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md :
> There are many reasons why we decided to go from the old single-header distribution model to a more standard library distribution model. The big one is compile-time performance, but moving over to a split header distribution model also improves the future maintainability and extendability of the codebase.
This PR also removes the inconsistent option in the FetchPackage CMake module:
```cmake
if( EXISTS "$ENV{${pkg}_DIR}" )
get_property( docString CACHE ${pkg}_DIR PROPERTY HELPSTRING )
set( ${pkg}_DIR $ENV{${pkg}_DIR} CACHE STRING "${docString}" FORCE )
add_subdirectory( ${${pkg}_DIR} ${CMAKE_CURRENT_BINARY_DIR}/${pkg} )
message( STATUS "Using ${pkg} from ${${pkg}_DIR}" )
```
=> Changes from Catch v2 to v3

examples/eigenvalues/example_eigenvalues.cpp, include/base/exceptionHandling.hpp, include/lapack/gehd2.hpp, include/lapack/gehrd.hpp, include/lapack/gelq2.hpp, include/lapack/gelqf.hpp, include/lapack/geqr2.hpp, include/lapack/lahqr.hpp, include/lapack/lahqr_shiftcolumn.hpp, include/lapack/larfb.hpp, include/lapack/larft.hpp, include/lapack/lascl.hpp, include/lapack/lauum_recursive.hpp, include/lapack/multishift_qr.hpp, include/lapack/potrf2.hpp, include/lapack/potrs.hpp, include/lapack/ung2r.hpp, include/lapack/unghr.hpp, include/lapack/ungl2.hpp, include/lapack/unm2r.hpp, include/lapack/unmqr.hpp, include/legacy_api/lapack/geqr2.hpp, include/legacy_api/lapack/larfb.hpp, include/legacy_api/lapack/larft.hpp, include/legacy_api/lapack/lascl.hpp, include/legacy_api/lapack/potrf.hpp, include/legacy_api/lapack/potrs.hpp, include/legacy_api/lapack/ung2r.hpp, include/legacy_api/lapack/unm2r.hpp, include/legacy_api/lapack/unmqr.hpp
Goes in the same line of thought of https://github.com/tlapack/tlapack/discussions/48#discussioncomment-2601890,
i.e., programming errors don't need to return a code, they instead generate exceptions for the programmer.
Also, the changes here avoid contradicting the standard up to C++17: `the number of arguments must not be less than the number of parameters (counting ...). Otherwise the program is ill-formed`. This rule changed with C++20 to `the number of arguments must not be less than the number of parameters (__not__ counting ...). Otherwise the program is ill-formed`.
See https://en.cppreference.com/w/cpp/preprocessor/replace
=> Homogenize the check for arguments

examples/eigenvalues/example_eigenvalues.cpp, include/tlapack/base/types.hpp, include/tlapack/blas/gemm.hpp, include/tlapack/blas/hemm.hpp, include/tlapack/blas/her2k.hpp, include/tlapack/blas/herk.hpp, include/tlapack/blas/symm.hpp, include/tlapack/blas/syr2k.hpp, include/tlapack/blas/syrk.hpp, include/tlapack/lapack/agressive_early_deflation.hpp, include/tlapack/lapack/multishift_qr_sweep.hpp, include/tlapack/legacy_api/blas/gemm.hpp, include/tlapack/legacy_api/blas/hemm.hpp, include/tlapack/legacy_api/blas/her2k.hpp, include/tlapack/legacy_api/blas/herk.hpp, include/tlapack/legacy_api/blas/symm.hpp, include/tlapack/legacy_api/blas/syr2k.hpp, include/tlapack/legacy_api/blas/syrk.hpp, include/tlapack/legacy_api/blas/trmm.hpp, include/tlapack/legacy_api/blas/trsm.hpp, include/tlapack/optimized/wrappers.hpp, performancetests/multishift_qr/profile_aed.cpp, performancetests/multishift_qr/profile_multishift_qr.cpp, test/include/testutils.hpp, test/src/test_gelq2.cpp, test/src/test_gelqf.cpp, test/src/test_lasy2.cpp
- gemm is the interface from BLAS. Since the interface in T-LAPACK is different, it makes sense to rename it.
- Also, by renaming it we could make different design choices.
`matrix_multiply` has two versions: one with and one without beta.
1. The first version computes `C := alpha*A*B + beta*C`;
2. The second computes `C := alpha*A*B`.
They are semantically different: in the first, C is [in,out]; in the second, C is [out] only.
Legacy `gemm` covers both functionalities depending on the value of beta (if beta is zero, use second expression).
The problem with the strategy adopted in `gemm` is: if beta evaluates to zero in some part of an algorithm and there are Infs or NaNs in C, those will not propagate.
The proposal is: if one wants to obtain the same behavior of gemm and
- `alpha=0` and …
=> Fix gemm legacy interface and propose a gemm with no beta

include/tlapack/base/types.hpp, include/tlapack/base/utils.hpp, include/tlapack/blas/herk.hpp, include/tlapack/blas/rotg.hpp, include/tlapack/lapack/agressive_early_deflation.hpp, include/tlapack/lapack/ladiv.hpp, include/tlapack/lapack/lahqr.hpp, include/tlapack/lapack/lahqr_eig22.hpp, include/tlapack/lapack/lahqr_schur22.hpp, include/tlapack/lapack/multishift_qr.hpp, include/tlapack/lapack/schur_swap.hpp, test/include/testutils.hpp, test/src/test_blocked_francis.cpp, test/src/test_unblocked_francis.cpp
=> Replace all std::complex<T> by complex_type<T>, except when T is float, double or long double

include/tlapack/blas/swap.hpp
Closes #134.
```c++
/** 
* Swap vectors, $x <=> y$.
* 
* @see swap( vectorX_t& x, vectorY_t& y )
* 
* @note This overload avoids unexpected behavior as follows.
*      Without it, the unspecialized call `swap( x, y )` using arrays with
*      `std::complex` entries would call `std::swap`, while `swap( x, y )`
*      using arrays with float or double entries would call `tlapack::swap`.
*      Use @c tlapack::swap(x,y) instead of @c swap(x,y) .
*/
template< class vector_t >
inline void swap( vector_t& x, vector_t& y ) { return swap<vector_t,vector_t>(x,y); }
```
=> New overloading to swap to avoid unexpected behavior

.github/workflows/cmake.yml, examples/CMakeLists.txt, examples/performance_eigen/CMakeLists.txt, examples/performance_eigen/Makefile, examples/performance_eigen/make.inc, examples/performance_eigen/performance_eigen.cpp, examples/performance_eigen/performance_tlapack.cpp, examples/performance_eigen/runWIthMKL.ipynb, include/tlapack/base/arrayTraits.hpp, include/tlapack/base/utils.hpp, include/tlapack/lapack/agressive_early_deflation.hpp, include/tlapack/lapack/lahqr.hpp, include/tlapack/lapack/lahr2.hpp, include/tlapack/lapack/multishift_qr_sweep.hpp, include/tlapack/lapack/schur_swap.hpp, include/tlapack/plugins/eigen.hpp, include/tlapack/plugins/legacyArray.hpp, include/tlapack/plugins/mdspan.hpp, test/src/test_optBLAS.cpp
This is another example testing the multishift QR. This time, we compare with the implementations in Eigen.
- When the flag `EIGEN_USE_MKL_ALL` is activated, Eigen uses `gees` from MKL.
- I have added a Jupyter notebook to this example, so the results are easier to reproduce.
=> Adds an example with Eigen3, testing multishift QR

include/tlapack/blas/dot.hpp, include/tlapack/blas/dotu.hpp, include/tlapack/blas/hemm.hpp, include/tlapack/blas/iamax.hpp, include/tlapack/blas/rotg.hpp, include/tlapack/blas/symm.hpp, include/tlapack/lapack/agressive_early_deflation.hpp, include/tlapack/lapack/gehrd.hpp, include/tlapack/lapack/lahqr.hpp, include/tlapack/lapack/lahqr_eig22.hpp, include/tlapack/lapack/lahqr_shiftcolumn.hpp, include/tlapack/lapack/lahr2.hpp, include/tlapack/lapack/larfg.hpp, include/tlapack/lapack/larft.hpp, include/tlapack/lapack/larnv.hpp, include/tlapack/lapack/lauum_recursive.hpp, include/tlapack/lapack/move_bulge.hpp, include/tlapack/lapack/multishift_qr.hpp, include/tlapack/lapack/potrf.hpp, include/tlapack/lapack/potrf2.hpp, include/tlapack/lapack/potrs.hpp, include/tlapack/lapack/schur_move.hpp, include/tlapack/lapack/trtri_recursive.hpp, include/tlapack/lapack/ung2r.hpp, include/tlapack/lapack/unghr.hpp, test/src/test_lasy2.cpp
One old discussion in the development team was:
Should we try to adopt a standard like `rzero` is the constant 0 with real type?
Then we name the variable `zero`, meaning it can have a complex type.
It turns out that, if we use `std::complex<real_t>` as the complex type, then we don't need to make any distinction. This is because
1. `std::complex<real_t>` operates with `real_t`, and
2. `std::complex<real_t>` have a constructor receiving `real_t`.
This PR highlights the assumption: a complex type should satisfy (1) and (2) to be used within \<T\>LAPACK routines. The routines in the master branch are already using those premises.
=> Constants 'one' and 'zero' have always real type

test/src/test_blocked_francis.cpp, test/src/test_gehrd.cpp, test/src/test_schur_move.cpp, test/src/test_schur_swap.cpp, test/src/test_unblocked_francis.cpp
The following piece of code
```c++
int n = GENERATE(1,2,3);
int m;
if (n > 1) {
int m = GENERATE(1,2,3,4);
}
else {
m = 1;
}
```
generates 12 Catch2 test sections. 4 of those sections have `m = 1` and `n = 1`. This is because `GENERATE` is a macro, and therefore it is executed regardless the value of `n > 1`.
This PR removes the repeated test cases that follow the pattern I gave above.
=> Removes a couple of repeated test cases

README.md
The badge should reflect the current state of the master branch. This wasn't the case. This PR fixes it.
=> Fix badge in the README.md

examples/performance_eigen/CMakeLists.txt
`set( $ENV{BLA_VENDOR} Intel10_64lp )` should be used instead of `set( BLA_VENDOR Intel10_64lp )` since `BLA_VENDOR` is an environment variable.
=> Fix BLA_VENDOR on a CMakelists.txt

CMakeLists.txt, include/tlapack/base/arrayTraits.hpp, include/tlapack/base/utils.hpp, include/tlapack/lapack/agressive_early_deflation.hpp, include/tlapack/lapack/gebd2.hpp, include/tlapack/lapack/gehd2.hpp, include/tlapack/lapack/gelq2.hpp, include/tlapack/lapack/geqr2.hpp, include/tlapack/lapack/lahqr.hpp, include/tlapack/lapack/lahqr_shiftcolumn.hpp, include/tlapack/lapack/lahr2.hpp, include/tlapack/lapack/larf.hpp, include/tlapack/lapack/larfb.hpp, include/tlapack/lapack/larfg.hpp, include/tlapack/lapack/move_bulge.hpp, include/tlapack/lapack/multishift_qr_sweep.hpp, include/tlapack/lapack/schur_swap.hpp, include/tlapack/lapack/ung2r.hpp, include/tlapack/lapack/unghr.hpp, include/tlapack/lapack/ungl2.hpp, include/tlapack/lapack/unm2r.hpp, include/tlapack/lapack/unmhr.hpp, include/tlapack/legacy_api/lapack/larf.hpp, include/tlapack/legacy_api/lapack/larfg.hpp, include/tlapack/plugins/legacyArray.hpp, include/tlapack/plugins/mdspan.hpp, include/tlapack/plugins/stdvector.hpp, test/src/CMakeLists.txt, test/src/test_larf.cpp
This PR adds more functionality to `larfg` and `larf` as follows:
- `larfg` now is able to store the Householder vectors in two ways: rowwise and columnwise. The latter is the functionality that is in LAPACK, used in QR, LQ and a large number of other routines. The rowwise mode is useful for RQ, QL, bidiagonalization, tridiagonalization, etc. In the rowwise mode, the conjugate of `v` is stored instead of `v` itself. See details in the documentation of `larfg`.
- `larf` has two new parameters: storeMode and direction. The first compatibilizes with the one from `larfg`. The second allows for the use of Householder vectors v = [1 x] and v = [x 1] more easily. That makes the algorithms for RQ and QL to be very similar to QR and LQ.
- `larf` has a new interface that receives `x, C0, C1` …
=> Adds storageMode on larfg and larf

include/tlapack/blas/iamax.hpp, include/tlapack/lapack/getrf_recursive.hpp
`iamax` had already options for NaN checking. This is an upgrade in the functionality of `iamax`. Now, we can pass the absolute value to be used `iamax`. For instance, we can call `iamax` using the usual complex norm
```c++
// x is a std::vector< std::complex<double> >
iamax_opts_t opts([](const std::complex<double>& x) { return std::abs(x); });
size_t idx = iamax( x, opts );
```
The LU recursive code now uses the usual complex norm. This is just so we can test the new functionality. We may need to add more tests. Moreover, we should decide how to use (or not use) this new functionality.
=> Introduces iamax that uses lambda function for abs

CONTRIBUTING.md, examples/lu/example_lu.cpp, include/tlapack/base/utils.hpp, include/tlapack/blas/rotg.hpp, include/tlapack/lapack/getrf.hpp, include/tlapack/lapack/getrf_level0.hpp, include/tlapack/lapack/getrf_recursive.hpp, include/tlapack/lapack/getri.hpp, include/tlapack/lapack/labrd.hpp, include/tlapack/lapack/lahr2.hpp, include/tlapack/legacy_api/lapack/geqr2.hpp, include/tlapack/legacy_api/lapack/ung2r.hpp, test/src/test_getrf.cpp, test/src/test_getri.cpp
Establishes some naming conventions for function arguments and template parameters. See the proposal on `CONTRIBUTING.md` at https://github.com/weslleyspereira/tlapack/blob/try-naming-conventions/CONTRIBUTING.md.
Closes #182.
=> Naming conventions

CONTRIBUTING.md, include/tlapack/base/StrongZero.hpp, include/tlapack/base/concepts.hpp, include/tlapack/base/constants.hpp, include/tlapack/base/types.hpp, include/tlapack/base/utils.hpp, include/tlapack/base/workspace.hpp, include/tlapack/lapack/aggressive_early_deflation.hpp, include/tlapack/lapack/lu_mult.hpp, include/tlapack/lapack/multishift_qr_sweep.hpp, include/tlapack/plugins/eigen.hpp, include/tlapack/plugins/legacyArray.hpp, include/tlapack/plugins/mdspan.hpp, include/tlapack/plugins/mpreal.hpp, include/tlapack/plugins/starpu.hpp, include/tlapack/plugins/stdvector.hpp, include/tlapack/starpu/filters.hpp, include/tlapack/starpu/utils.hpp
Establishes directions to when using `assert()` and `tlapack_check()` in CONTRIBUTING.md. Also, use noexcept more consistently throughout the code.
Helpful links:
- https://en.cppreference.com/w/cpp/error/assert
- https://en.cppreference.com/w/cpp/language/noexcept_spec
=> Use noexcept, assert() and tlapack_check() consistently

.github/workflows/cmake.yml, CMakeLists.txt, include/tlapack/base/concepts.hpp, include/tlapack/plugins/gnuquad.hpp, test/include/testdefinitions.hpp, test/src/CMakeLists.txt
This PR adds compatibility with the GNU quadruple precision type `__float128`. See https://gcc.gnu.org/onlinedocs/gcc-6.5.0/libquadmath.pdf
More functionality -> more tests -> more bugs solved. In this case, I realized we actually need `sqrt()` for complex data types. So, this PR also adds `sqrt()` to the `Complex` concept.
Closes #240
=> Adds compatibility with GNU quad precision

examples/CMakeLists.txt, examples/README.md, examples/create_float_library/CMakeLists.txt, examples/create_float_library/Makefile, examples/create_float_library/README.md, examples/create_float_library/main.cpp, examples/create_float_library/make.inc, examples/create_float_library/tlapack_EigenMatrixXf.cpp, examples/create_float_library/tlapack_EigenMatrixXf.hpp, include/tlapack/plugins/gnuquad.hpp, include/tlapack/starpu/filters.hpp
In this example, we show how to create a static library with single precision from the \<T\>LAPACK library. We use single precision `float` and the data structures from the [Eigen](https://eigen.tuxfamily.org) library, namely, `Eigen::MatrixXf` and `Eigen::VectorXf`.
=> Adds example for building a static library from \<T\>LAPACK

include/tlapack/base/exceptionHandling.hpp, include/tlapack/base/utils.hpp, include/tlapack/lapack/hasinf.hpp, include/tlapack/lapack/hasnan.hpp, include/tlapack/lapack/potrf2.hpp, include/tlapack/lapack/potrf_blocked.hpp, include/tlapack/lapack/potrf_blocked_right_looking.hpp, include/tlapack/lapack/trtri_recursive.hpp, test/src/test_optBLAS.cpp, test/src/test_utils.cpp
- Removes confusing `tlapack_warn_infs_in_vector()` and `tlapack_warn_nans_in_vector()`.
- Macro `tlapack_error_internal()` is renamed to `tlapack_error_if()`.
- Organize utils.hpp. Moves `hasinf()` and `hasnan()` to separate files.
=> Some cleanup.

.github/workflows/deploy_pages.yml, .github/workflows/doxygen.yml
We are using the most version from Doxygen. Building from source is too much slow. This PR moves to "install the binary" mode.
=> Install Doxygen binaries instead of building from source

.github/workflows/cmake.yml, test/src/CMakeLists.txt
I noticed that we were actually not testing the type `__float128` in our CI. This PR fixes the CI script.
=> Properly test float128 in the CI

CMakeLists.txt
We require at least v2023.01.00 of lapackpp for lartg, but currently, cmake was fixed to v2022. This PR updates the config to require v2023
=> update lapackpp version in cmake

examples/access_types/CMakeLists.txt, examples/cpp_visualizer/CMakeLists.txt, examples/create_float_library/CMakeLists.txt, examples/cwrapper_gemm/CMakeLists.txt, examples/eigen/CMakeLists.txt, examples/eigenvalues/CMakeLists.txt, examples/fortranModule_caxpy/CMakeLists.txt, examples/fortranWrapper_ssymm/CMakeLists.txt, examples/gemm/CMakeLists.txt, examples/geqr2/CMakeLists.txt, examples/lu/CMakeLists.txt, examples/mdspan/CMakeLists.txt, examples/performance_eigen/CMakeLists.txt, examples/potrf/CMakeLists.txt, examples/starpu/CMakeLists.txt
Update minimum CMake requirements to CMake 3.5 as compatibility with CMake < 3.5 will be removed from a future version of CMake.
=> Update minimum CMake requirements to CMake 3.5

include/tlapack/lapack/lahqz_eig22.hpp, include/tlapack/lapack/rot_sequence.hpp, test/src/test_qz_eig22.cpp
The typo was identified by the windows build in the CI. Great to see that we have more information by testing on different platforms.
=> Fix typo and warnings

CONTRIBUTING.md, README.md, include/tlapack/lapack/lahqr.hpp, include/tlapack/lapack/lahqr_schur22.hpp, include/tlapack/lapack/lasy2.hpp, include/tlapack/lapack/multishift_qr.hpp, include/tlapack/lapack/potrf.hpp, include/tlapack/lapack/qr_iteration.hpp, test/src/test_qr_algorithm.cpp
Explains the current design for the return types.
Also,
- Uses `if constexpr()` in `lahqr()` and removes `lahqr_schur22()` implementation for complex types.
- `lasy2()` sets `scale=0; xnorm=0` if `n1 == 0` or `n2 == 0`. Closes #297.
=> Explain return types in the contributing guidelines

include/tlapack/plugins/debugutils.hpp
The debugutils are often called using non-typechecked c calls via gdb.
If you accidentally call one of those functions using an unitialized matrix, a vector, the wrong type of matrix, ... it can result in infinite/very large loops.
This PR limits the loop to 100 iterations, which is larger than anything we will realistically want to debug and avoids having to restart the debugger in case of such mistakes.
=> limit debugutils to size 100 matrices

include/tlapack/lapack/rot_sequence3.hpp, test/src/CMakeLists.txt, test/src/test_rot_sequence3.cpp
In the paper: "Restructuring the Tridiagonal and Bidiagonal QR Algorithms for Performance" F. G. Van Zee, R. A. Van de Geijn, G. Quintana-Orti
The authors describe a wavefront algorithm to efficiently apply givens rotations. If we can apply multiple sequences of rotations at a similar flop rate as a gemm call, we can greatly speed up things like singular value and hermitian eigenvalue problems if using the implicit QR algorithm.
Some speed comparisons are below:
- CPU: i7-1255U
- Number of columns in C and S (number of sequences of rotations to apply): 40
- Matrix A is square and of size n
- Timing is average of 8 runs with 2 warmup runs
From the left side (inherently less efficient because matrices are column major)
| n        | blocked(s) | unblocked(s) |
|------ …
=> implement wavefront algorithm for sequence of rotations

.github/workflows/codeql.yml
CodeQL installs Eigen automatically. This is troublesome, since \<T\>LAPACK doesn't work with the latest release of Eigen. See https://github.com/tlapack/tlapack?tab=readme-ov-file#dependencies-on-other-projects.
This PR installs the correct version of Eigen before running the CodeQL analysis.
=> Fix CodeQL tests with Eigen3

include/tlapack/plugins/debugutils.hpp, test/src/testutils.cpp
I often find myself in a situation where only the Eigen::Half tests are failing. Which is annoying because there are no pretty printers for Eigen::Half in gdb.
This PR extends the debugutils for visualizing matrix to vectors and adds functions for Eigen::Half.
=> add debugutils for eigen::half and vectors

include/tlapack/lapack/steqr.hpp
If n=1, then "if (want_z) Z(0, 0) = one;" overwrites the Z of the tridiagonal reduction. The current interface says that, if wantz, then Z must be initialized in input, so it could be better that Z is not overwritten in the n=1 case. 
Setting Z(0,0) to one in STEQR is a correct behavior.  
But we can also leave Z(0,0) as is. For example, Z(0,0) could be an e^iθ in input and it would be OK to leave it as such. (This would be the output of a weird choice for an n=1 tridiagonalization algorithm but valid.)
I do not feel too strongly about either way. All in all, I think a quick return is better.
=> change behavior for 1-by-1 matrix Z for case n=1 for STEQR if wantz
