tlapack/tlapack

- include/legacy_api/legacyArray.hpp
- include/plugins/tlapack_legacyArray.hpp
closes #37 
Adds a few assertions to the matrix access
> add some assertions to matrix access

- include/lapack/larfb.hpp
- include/lapack/larft.hpp
- include/lapack/potrf.hpp
This PR also improve readability of `larft`.
> Fix out-of-bounds on larfb, larft and potrf

- include/lapack/lasy2.hpp
- include/lapack/schur_move.hpp
- include/lapack/schur_swap.hpp
- include/tlapack.hpp
- test/src/test_lasy2.cpp
- test/src/test_schur_move.cpp
- test/src/test_schur_swap.cpp
Implement 1x1 and 2x2 sylvester solver ( but not 1x2 and 2x1)
Implement schur swap
> Schur swap

- include/lapack/unm2r.hpp
- include/lapack/unmqr.hpp
Resolves #61. Thanks @thijssteel !
> Fixes a bug in unm2r and unmqr

- .github/workflows/cmake.yml
This PR adds one workflow that uses oneMKL as optimized BLAS library.
> Add workflow with MKL

- include/base/utils.hpp
- include/legacy_api/blas.hpp
- test/src/test_optBLAS.cpp
Add tester for optBLAS and fix bugs
> Add tester for optBLAS and fix bugs

- .github/workflows/cmake.yml
> don't run on push

- include/blas/gemm.hpp
Jim mentioned in the last ballistic call that this is the intented behavior of gemm.
> check for beta == o in gemm to avoid nan propagation

- include/base/utils.hpp
Removes ugly static_assert, and compatibilize with the rest of the library.
> Removes ugly static_assert

- include/base/types.hpp
- include/lapack/gelqf.hpp
- include/lapack/ungl2.hpp
One idea to print enum classes like `Uplo`. Related to https://github.com/tlapack/tlapack/pull/95#discussion_r888618945 .
It is a draft. If it is a good idea, I can make it for the other enums.
> Defines the behavior of operator << for the enum Uplo and for Layout

- .github/workflows/cmake.yml
- CMakeLists.txt
- include/base/utils.hpp
Also,
- try stop enforcing C++14.
- removes a if guards for C++11. C++14 is used in other parts without the guards.
> Add tests for BLIS

- test/src/test_trtri.cpp
Remove unused comments I forgot to deal with before merging #95.
> Removing unused comments

- .github/workflows/cmake.yml
- include/tlapack/blas/her.hpp
- include/tlapack/blas/her2.hpp
- include/tlapack/blas/her2k.hpp
- include/tlapack/blas/herk.hpp
Closes #102 with @langou's idea.
> Remove unnecessary complex multiplications

- include/tlapack.hpp
- include/tlapack/lapack/getrf.hpp
- include/tlapack/lapack/getrf2.hpp
- include/tlapack/lapack/getri.hpp
- include/tlapack/lapack/ul_mult.hpp
- test/src/CMakeLists.txt
- test/src/test_getrf.cpp
- test/src/test_getrf2.cpp
- test/src/test_getri.cpp
- test/src/test_ul_mult.cpp
add lu decomposition and tests
> lu decomposition

- .github/workflows/cmake.yml
- test/CMakeLists.txt
- test/blaspp/blas/util.hh
- test/blaspp/test.cpp
- test/src/CMakeLists.txt
Last changes on testBLAS made it independent from \<T\>LAPACK. This changes make the two projects compatible again
> Compatibilize with last changes on testBLAS

- include/tlapack/lapack/agressive_early_deflation.hpp
- include/tlapack/lapack/gebd2.hpp
- include/tlapack/lapack/gehd2.hpp
- include/tlapack/lapack/gelq2.hpp
- include/tlapack/lapack/geqr2.hpp
- include/tlapack/lapack/lahr2.hpp
- include/tlapack/lapack/larf.hpp
- include/tlapack/lapack/ung2r.hpp
- include/tlapack/lapack/ungl2.hpp
- include/tlapack/lapack/unm2r.hpp
> Adds direction to larf

- .github/workflows/cmake.yml
- examples/potrf/CMakeLists.txt
- test/lapackpp/CMakeLists.txt
- test/lapackpp/cmake/FindLAPACKE.cmake
The job `build-with-blis` works when I run it using `https://github.com/nektos/act` in my local machine. The problem may be associated with the Docker image from Github.
> Fix cmake.yml so that build-with-blis works

- .github/workflows/cmake.yml
- .github/workflows/doxygen.yml
- README.md
- docs/Doxyfile.in
- include/tlapack/base/arrayTraits.hpp
- include/tlapack/base/exceptionHandling.hpp
- include/tlapack/blas/syr2k.hpp
- include/tlapack/blas/syrk.hpp
- include/tlapack/lapack/lahqr.hpp
- include/tlapack/lapack/lange.hpp
- include/tlapack/lapack/lanhe.hpp
- include/tlapack/lapack/lansy.hpp
- include/tlapack/lapack/lantr.hpp
- include/tlapack/lapack/larfb.hpp
- include/tlapack/lapack/lascl.hpp
- include/tlapack/lapack/multishift_qr_sweep.hpp
- include/tlapack/lapack/schur_swap.hpp
- include/tlapack/legacy_api/lapack/lacpy.hpp
- include/tlapack/legacy_api/lapack/lange.hpp
- include/tlapack/legacy_api/lapack/lantr.hpp
- include/tlapack/legacy_api/lapack/larfb.hpp
- include/tlapack/legacy_api/lapack/larft.hpp
- include/tlapack/legacy_api/lapack/lascl.hpp
- include/tlapack/legacy_api/lapack/laset.hpp
- include/tlapack/legacy_api/lapack/lassq.hpp
- include/tlapack/legacy_api/lapack/unm2r.hpp
- include/tlapack/plugins/abstractArray.hpp
- include/tlapack/plugins/debugutils.hpp
The tests will run every time a new commit appears. Those tests verify if the modifications introduce warnings in the documentation.
> Fix warnings on documentation, and adds test for it

- README.md
- include/tlapack/lapack/lahqr.hpp
- include/tlapack/lapack/multishift_qr.hpp
- test/src/test_blocked_francis.cpp
... and adds more description about tests.
> Fix name of contributor in a couple of files

- test/src/test_blocked_francis.cpp
- test/src/test_gehrd.cpp
This improves the readability of two tests from #167
> Improves the readability of two test cases

- README.md
> Adds list with current functionality in the software

- README.md
Suggestion: https://github.com/tlapack/tlapack/pull/170#issuecomment-1401512020
Thanks @thijssteel !
> Adds more functionality to the README list as suggested by @thijssteel

- CONTRIBUTING.md
- test/src/test_blocked_francis.cpp
- test/src/test_gebd2.cpp
- test/src/test_gehrd.cpp
- test/src/test_gelq2.cpp
- test/src/test_gelqf.cpp
- test/src/test_getrf.cpp
- test/src/test_getri.cpp
- test/src/test_larf.cpp
- test/src/test_lasy2.cpp
- test/src/test_lauum.cpp
- test/src/test_lu_mult.cpp
- test/src/test_potrf.cpp
- test/src/test_schur_move.cpp
- test/src/test_schur_swap.cpp
- test/src/test_transpose.cpp
- test/src/test_trtri.cpp
- test/src/test_ul_mult.cpp
- test/src/test_unblocked_francis.cpp
- test/src/test_unmhr.cpp
Come back with `DYNAMIC_SECTION` as suggested in https://github.com/tlapack/tlapack/pull/147#issuecomment-1437141204. Thanks @thijssteel !
> Undo part of #147

- test/src/test_gebd2.cpp
- test/src/test_unmhr.cpp
> Applies recomendation from @thijssteel in #204

- include/tlapack/plugins/debugutils.hpp
- test/include/testutils.hpp
- test/src/CMakeLists.txt
- test/src/test_geql2.cpp
- test/src/test_geqlf.cpp
- test/src/test_unm2l.cpp
- test/src/test_unm2r.cpp
- test/src/test_unml2.cpp
- test/src/test_unmlq.cpp
- test/src/test_unmql.cpp
- test/src/test_unmqr.cpp
- test/src/test_unmr2.cpp
- test/src/test_unmrq.cpp
- test/src/testutils.cpp
Closes #96 using https://github.com/tlapack/tlapack/issues/96#issuecomment-1489035665.
> Move part of debugutils.hpp to testutils.cpp

- include/tlapack/base/legacyArray.hpp
- include/tlapack/lapack/lascl.hpp
- include/tlapack/plugins/legacyArray.hpp
- test/include/TestUploMatrix.hpp
> Protect const entry access in legacyMatrix

- include/tlapack.hpp
- include/tlapack/lapack/getrf_level0.hpp
- include/tlapack/lapack/getrf_recursive.hpp
- include/tlapack/lapack/ladiv.hpp
- include/tlapack/lapack/larfg.hpp
- include/tlapack/lapack/rscl.hpp
- test/include/NaNPropagComplex.hpp
- test/src/CMakeLists.txt
- test/src/test_rscl.cpp
> Implements the reciprocal scaling

- test/src/CMakeLists.txt
- test/src/test_ladiv.cpp
> Adds test for ladiv

- include/tlapack/blas/gemv.hpp
- include/tlapack/blas/trmv.hpp
- include/tlapack/blas/trsv.hpp
- include/tlapack/lapack/conjugate.hpp
> Fix bug in Op::Conj

- include/tlapack/base/concepts.hpp
- include/tlapack/lapack/lahqr.hpp
- include/tlapack/lapack/move_bulge.hpp
- include/tlapack/lapack/schur_swap.hpp
- include/tlapack/plugins/legacyArray.hpp
- include/tlapack/plugins/mdspan.hpp
- include/tlapack/plugins/starpu.hpp
Two new concepts for "constructable" matrices and vectors. (We can use a better name in future.)
Note to self: Having those concepts working in the code is also helpful for testing our plugins.
> Adds Constructable concepts

- include/tlapack/lapack/FrancisOpts.hpp
- include/tlapack/lapack/agressive_early_deflation.hpp
- include/tlapack/lapack/multishift_qr.hpp
Bug introduced when making FrancisOpts a non-template class
> Fix bug in the inclusion of FrancisOpts

- examples/eigenvalues/profile_aed.cpp
- include/tlapack.hpp
- include/tlapack/lapack/aggressive_early_deflation.hpp
- include/tlapack/lapack/multishift_qr.hpp
> Fix the wording agressive to aggressive

- .github/workflows/cmake.yml
- CMakeLists.txt
- examples/access_types/README.md
- examples/access_types/make.inc
- examples/create_float_library/make.inc
- examples/cwrapper_gemm/README.md
- examples/cwrapper_gemm/make.inc
- examples/eigen/README.md
- examples/eigen/make.inc
- examples/eigenvalues/make.inc
- examples/fortranModule_caxpy/CMakeLists.txt
- examples/fortranModule_caxpy/Makefile
- examples/fortranModule_caxpy/README.md
- examples/fortranModule_caxpy/make.inc
- examples/fortranWrapper_ssymm/CMakeLists.txt
- examples/fortranWrapper_ssymm/Makefile
- examples/fortranWrapper_ssymm/README.md
- examples/fortranWrapper_ssymm/make.inc
- examples/gemm/README.md
- examples/gemm/make.inc
- examples/geqr2/README.md
- examples/geqr2/make.inc
- examples/mdspan/README.md
- examples/mdspan/make.inc
- examples/performance_eigen/make.inc
- src/CMakeLists.txt
This job builds and executes the examples as separate projects. The main purpose here is to assure that the examples work as separate projects. Moreover, some examples have a build system based on Makefile. This PR also tests the Makefile system.
> Adds new test to the Github Actions: build-examples-separately

- include/tlapack/plugins/eigen.hpp
- test/src/test_concepts.cpp
> Fix definition of tlapack::size() for Eigen types

- README.md
This will help us identify possibilities of improvement in the library. It is also a good badge to have. I think we are in good shape with this project so far.
> Adds OpenSSF Best Practices Badge

- .github/workflows/cmake.yml
- include/tlapack/lapack/FrancisOpts.hpp
- include/tlapack/lapack/aggressive_early_deflation.hpp
- include/tlapack/lapack/multishift_qr.hpp
- include/tlapack/plugins/gnuquad.hpp
Another attempt to fix the most recent bugs in the CI for Windows.
> Fixes windows build

- CONTRIBUTING.md
- include/tlapack/blas/rotg.hpp
- include/tlapack/lapack/gesvd.hpp
- include/tlapack/lapack/getrf_recursive.hpp
- include/tlapack/lapack/lahqz.hpp
- include/tlapack/lapack/lasy2.hpp
- include/tlapack/lapack/potf2.hpp
- include/tlapack/starpu/MatrixEntry.hpp
- test/src/test_qz_algorithm.cpp
This PR makes all TO-DO's visible in the Doxygen documentation in the page: https://tlapack.github.io/tlapack/todo.html.
> Make all todo's visible in documentation

- .github/workflows/cmake.yml
In a recent PR, I introduced a bug in the CI. This PR solves it.
> Fix a bug in cmake.yml

- .github/workflows/doxygen.yml
- include/tlapack/lapack/lahqz_shiftcolumn.hpp
- The CI was not checking the correct directory for errors. So, this PR fixes it.
- Doxygen has trouble to generate the documentation for two routines with the exact same signature but different types. Example below. This PR fixes it.
Doxygen will merge the two documentations below:
```c++
/** Documentation 1 */
template <TLAPACK_MATRIX matrix_t,
TLAPACK_VECTOR vector_t,
enable_if_t<is_real<type_t<matrix_t>>, bool> = true>
int lahqz_shiftcolumn(const matrix_t& A,
const matrix_t& B,
vector_t& v,
complex_type<type_t<matrix_t>> s1,
complex_type<type_t<matrix_t>> s2,
type_t<matrix_t> beta1,
type_t<matrix_t> beta2);
/** Documentation 2 */
template <TLAPACK_MATRIX matrix_t,
TLAPACK_VECTOR vector_t,
enable_if_t<is_complex<type_t<matrix_t>>, bool> = true>
int lahqz_shiftcolumn(const matrix_t& A, …
```
> Fix doxygen checkup

- README.md
Thanks for the fix @Xuan-1998!
> Fix README.md thanks to @Xuan-1998

- CONTRIBUTING.md
- README.md
- Adds more information to CONTRIBUTING.md.
- Separate explanations for building and installing \<T\>LAPACK in README.md.
> Update contributing notes and README

- .github/workflows/cmake.yml
See the bug in https://github.com/tlapack/tlapack/actions/runs/6868061223/job/18679777543.
This PR fixes it by using gfortran instead.
> Fix ifx bug in the CI

- include/tlapack/lapack/hetd2.hpp
- include/tlapack/lapack/ungtr.hpp
- test/src/CMakeLists.txt
- test/src/test_hetd2.cpp
Since #189 was almost done, I copied the files, made them compile with the latest version of the library and handled some edge cases<
> Tridiagonal reduction

- include/tlapack/lapack/lu_mult.hpp
- include/tlapack/lapack/mult_llh.hpp
- test/src/CMakeLists.txt
- test/src/test_mult_llh.cpp
- test/src/test_potrf.cpp
This contributes llh. We need uhu. Someone else with contribute uhu in include. I will finish the integration of uhu with testing then. Please consider for merge.
> Try mult llh and uhu

- .github/workflows/cmake.yml
> Switch from windows-2019 to windows-latest
